repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        name: Format code

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: Lint code
        additional_dependencies: ["flake8-use-fstring", "flake8-bugbear"]
