pipelines:
  custom:
    test_after_script:
      - step:
          name: Test After Script
          image: alpine
          services:
            - docker
          script:
            - cat /etc/os-release
            - docker --version
            - exit 2
          after-script:
            - echo "Doing cleanup"
            - echo "Exit Code was ${BITBUCKET_EXIT_CODE}"
