definitions:
  caches:
    service1: ~/.cache/service1
    invalid: $HOME/.cache/non-existing-folder

image: alpine

pipelines:
  custom:
    test_success:
      - step:
          name: Test Success
          script:
            - cat /etc/os-release
            - id

    test_failure:
      - step:
          name: Test Failure
          script:
            - cat /etc/os-release
            - id
            - exit 69

    test_after_script:
      - step:
          name: Test After Script
          script:
            - cat /etc/os-release
            - exit 2
          after-script:
            - echo "Doing cleanup"
            - echo "Exit Code was ${BITBUCKET_EXIT_CODE}"

    test_cache_alpine:
      - step:
          name: Create Cache
          caches:
            - service1
          script:
            - export CACHE_DIR=$HOME/.cache/service1
            - sh -c 'if [ -d "${CACHE_DIR}" ]; then rm -rf "${CACHE_DIR}"; fi'
            - mkdir -p "${CACHE_DIR}"
            - dd if=/dev/random of=${CACHE_DIR}/a bs=2048 count=1
            - dd if=/dev/random of=${CACHE_DIR}/b bs=2048 count=1
            - md5sum ${CACHE_DIR}/* > MD5SUM
            - mv MD5SUM ${CACHE_DIR}/
      - step:
          name: Ensure Cache Exists
          caches:
            - service1
          script:
            - export CACHE_DIR=$HOME/.cache/service1
            - md5sum -c ${CACHE_DIR}/MD5SUM

    test_cache_debian:
      - step:
          name: Create Cache
          image: debian:buster
          caches:
            - service1
          script:
            - export CACHE_DIR=$HOME/.cache/service1
            - sh -c 'if [ -d "${CACHE_DIR}" ]; then rm -rf "${CACHE_DIR}"; fi'
            - mkdir -p "${CACHE_DIR}"
            - dd if=/dev/random of=${CACHE_DIR}/a bs=2048 count=1
            - dd if=/dev/random of=${CACHE_DIR}/b bs=2048 count=1
            - md5sum ${CACHE_DIR}/* > MD5SUM
            - mv MD5SUM ${CACHE_DIR}/
      - step:
          name: Ensure Cache Exists
          image: debian:buster
          caches:
            - service1
          script:
            - export CACHE_DIR=$HOME/.cache/service1
            - md5sum -c ${CACHE_DIR}/MD5SUM

    test_invalid_cache:
      - step:
          name: Test Invalid Cache
          caches:
            - invalid
          script:
            - exit 0

    test_artifacts:
      - step:
          name: Create Artifacts
          artifacts:
            - ~/artifact-in-home
            - valid-folder/**
            - invalid-folder/**
            - folder-name
            - file-name
          script:
            - echo foo > ~/artifact-in-home
            - mkdir -p valid-folder/sub/sub/sub folder-name
            - touch valid-folder/a valid-folder/b valid-folder/sub/c
            - touch folder-name/a folder-name/b
            - touch file-name
      - step:
          name: Validate Artifacts
          script:
            - ls -R
            - "[ -e valid-folder/a ] || exit 1"
            - "[ -e valid-folder/b ] || exit 1"
            - "[ -e valid-folder/sub/c ] || exit 1"
            - "[ -e file-name ] || exit 1"

            - "[ -e ~/artifact-in-home ] && exit 1"
            - "[ -d valid-folder/sub/sub ] && exit 1"
            - "[ -d invalid-folder ] && exit 1"
            - "[ -d folder-name ] && exit 1"
            - "[ -d root ] && exit 1"
            - exit 0
      - step:
          name: Test no artifacts to save
          artifacts:
            - foobar/**
          script:
            - exit 0

    test_deployment_environment:
      - step:
          name: Test Bitbucket Deployment Environment
          deployment: Foo
          script:
            - 'echo "Deployment Environment: ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"'
            - if [ "${BITBUCKET_DEPLOYMENT_ENVIRONMENT:-}" != "Foo" ]; then
            -   exit 1
            - fi

    test_docker_in_docker:
      - step:
          name: Test docker in docker
          script:
            - apk --no-cache add curl
            - docker run -d --name nginx -p 8080:80 nginx:alpine
            - sleep 2
            - curl --fail 127.0.0.1:8080
          services:
            - docker
          caches:
            - docker
      - step:
          name: Ensure docker cache
          script:
            - docker image inspect nginx:alpine -f "{{.RepoTags}}"
          services:
            - docker
          caches:
            - docker

    test_run_as_user:
      - step:
          name: Test Default User
          script:
            - 'if [ "$(id -u)" != "0" ]; then'
            -   'echo "User is $(id)"'
            -    exit 1
            - fi

            - touch foo
            - 'if [ "$(stat -c "%u" foo)" != "0" ]; then'
            -   'echo "File is $(stat foo)"'
            -    exit 1
            - fi
      - step:
          name: Test Custom User
          image:
            name: alpine
            run-as-user: 1000
          script:
            - 'if [ "$(id -u)" != "1000" ]; then'
            -   'echo "User is $(id)"'
            -    exit 1
            - fi

            - touch foo
            - 'if [ "$(stat -c "%u" foo)" != "1000" ]; then'
            -   'echo "File is $(stat foo)"'
            -    exit 1
            - fi

    test_pipeline_variables:
      - variables:
          - name: FILENAME
          - name: MESSAGE
          - name: EMPTY
      - step:
          name: Test Pipeline Variables
          artifacts:
            - output/**
          script:
            - 'if [ -n "${EMPTY}" ]; then exit 1; fi'
            - 'echo "FILENAME: ${FILENAME:?}"'
            - 'echo "MESSAGE: ${MESSAGE:?}"'
            - mkdir output
            - 'echo "${MESSAGE}" > "output/${FILENAME}"'

    test_manual_trigger:
      - step:
          name: Setup
          artifacts:
            - setup_done
          script:
            - touch setup_done
      - step:
          name: Manual Step
          trigger: manual
          script:
            - echo "This is the manual step"
