pipelines:
  custom:
    test_install_binaries:
      - step:
          name: Install binaries on debian
          image: debian:stable-slim
          script:
            - bash --version
            - docker --version
            - git --version
      - step:
          name: Install binaries on alpine
          image: alpine
          script:
            - bash --version
            - docker --version
            - git --version

definitions:
  services:
    s1:
      image: redis:6-alpine
    s2:
      image: postgres:9
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
