pipelines:
  custom:
    test_after_script:
      - step:
          name: Test After Script
          image: alpine
          script:
            - bash --version
            - docker --version
            - exit 2
          after-script:
            - echo "Doing cleanup"
            - echo "Exit Code was ${BITBUCKET_EXIT_CODE}"
