[tool.poetry]
name = "pipeline-runner"
version = "0.1.0"
description = "Run a bitbucket pipeline locally"
authors = ["Mathieu Lemay <mathieu.lemay@broadsign.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
